INSERT INTO `T_SYSPARA` VALUES ('exchange_apply_order_buy_fee', 'exchange_apply_order_buy_fee', null, '0', '100', '2', '币币交易买入手续费');

INSERT INTO `T_SYSPARA` VALUES ('exchange_apply_order_sell_fee', 'exchange_apply_order_sell_fee', null, '0.01', '100', '2', '币币交易卖出手续费');


INSERT INTO `T_SYSPARA` VALUES ('exchange_order_open', 'exchange_order_open', null, 'true', '100', '2', '币币交易开关(true开启，false关闭)');